version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://64.226.67.215:8000
    networks:
      - fiyatiq-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-1.5-flash
      - GEMINI_TEMPERATURE=0.2
      - GEMINI_MAX_TOKENS=2048
    volumes:
      - ./backend/.env:/app/.env:ro
    networks:
      - fiyatiq-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
    depends_on:
      - frontend
      - backend
    networks:
      - fiyatiq-network
    restart: unless-stopped

networks:
  fiyatiq-network:
    driver: bridge
